config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  root "items#index"
  resources :items, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :orders, only: [:new, :create]
    get '/:name', controller: 'items', action: 'edit'
    get 'search', on: :collection
  end



  devise_scope :user do
    get "/users/sign_up/registration", to: "users/registrations#index", as: "user_registration_index"
    get "/users/sign_up/basic-infomation", to: "users/registrations#basic_information", as: "user_registration_basic_infomation"
    get "/users/sign_up/sns-basic-infomation", to: "users/registrations#sns_basic_information", as: "user_registration_sns_basic_infomation"
    get "/users/sign_up/residence", to: "users/registrations#residence", as: "user_registration_residence"
    get "/users/sign_up/payment", to: "users/registrations#payment", as: "user_registration_payment"
    post '/users/sign_up/payment/finish', to: "users/registrations#finish", as: "user_registration_finish"
    patch 'users/:name', controller: 'users/registrations', action: 'update'
  end

  resource :users, only: [:show, :update]

  get 'users/:name', controller: 'users', action: 'edit'
  get 'users/:name', controller: 'users/registrations', action: 'edit'
end

app/views/shared/_flash_deleted.html.haml
- if flash[:notice_deleted]
  :javascript
    toastr.options = {
      "progressBar": true,
      "positionClass": "toast-top-full-width",
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }
    toastr.info("商品を削除しました。")

app/views/shared/_flash_exhibition_completed.html.haml
- if flash[:notice_exhibition_completed]
  :javascript
    toastr.options = {
      "progressBar": true,
      "positionClass": "toast-top-full-width",
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    };
    toastr.success("あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。", "出品が完了しました")

app/views/shared/_flash_updated.html.haml
- if flash[:notice_updated]
  :javascript
    toastr.options = {
      "progressBar": true,
      "positionClass": "toast-top-full-width",
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }
    toastr.success("商品の情報を更新しました。")

app/views/shared/_footer.html.haml
%footer.global-footer

  .footer-wrapper
    %ul
      %li.download-app
        = link_to "", class: "app-icon" do
          = image_tag("mercari_icon.png", width: "35", alt: "download-app", style: "vertical-align:bottom")
          今すぐ無料ダウンロード！

      %li.footer-cell
        %h2.footer-head メルカリについて
        %ul.detail
          %li
            = link_to "会社概要(運営会社)", "#"
          %li
            = link_to "プライバシーポリシー", "#"
          %li
            = link_to "メルカリ利用規約", "#"
          %li
            = link_to "メルカリ利用規約・有償ポイントに関する特約", "#"
          %li
            = link_to "あんしんスマホサポート制度に関する利用規約", "#"
          %li
            = link_to "コンプライアンスポリシー", "#"
          %li
            = link_to "個人データの安全管理に係る基本方針", "#"
          %li
            = link_to "特定商取引に関する表記", "#"
          %li
            = link_to "資金決済法に基づく表示", "#"
          %li
            = link_to "法令順守と犯罪抑止のために", "#"
          %li
            = link_to "採用情報", "#"

      %li.footer-cell
        %h2.footer-head メルカリを見る
        %ul.detail
          %li
            = link_to "カテゴリ一覧", "#"
          %li
            = link_to "ブランド一覧", "#"
          %li
            = link_to "出品地域一覧", "#"
          %li
            = link_to "公式ブログ", "#"
          %li
            = link_to "公式Twitter", "#"
          %li
            = link_to "公式Facebook", "#"

      %li.footer-cell
        %h2.footer-head ヘルプ＆ガイド
        %ul.detail
          %li
            = link_to "メルカリガイド", "#"
          %li
            = link_to "メルカリロゴ利用ガイドライン", "#"
          %li
            = link_to "お知らせ", "#"
          %li
            = link_to "楽々メルカリ便とは", "#"
          %li
            = link_to "ゆうゆうメルカリ便とは", "#"
          %li
            = link_to "大型らくらくメルカリ便とは", "#"
          %li
            = link_to "車体取引ガイド", "#"
          %li
            = link_to "返品・返金ポリシー", "#"
          %li
            = link_to "メルカリあんしん・あんぜん宣言！", "#"
          %li
            = link_to "偽ブランド品撲滅への取り組み", "#"
          %li
            = link_to "メルカリボックス", "#"

      %li.footer-cell
        %h2.footer-head 国
        %ul.detail
          %li
            = link_to "", class: "lang-nav" do
              = image_tag("flag_us.png", width: "22", height: "22", alt: "flag-us", style: "vertical-align:bottom")
              United States

          %li
            = link_to "", class: "lang-nav" do
              = image_tag("flag_uk.png", width: "22", height: "22", alt: "flag-uk", style: "vertical-align:bottom")
              United Kingdom
          %li
            = link_to "", class: "lang-ja" do
              = image_tag("flag_jp.png", width: "22", height: "22", alt: "flag-jp", style: "vertical-align:bottom")
              日本

  = link_to image_tag("footer-logo.svg", width: "124", height: "33", alt: "フッターロゴ"), root_path, class: "footer-logo"

  .copyright
    &copy; 2019 freemarket_42nagoya

app/views/shared/_header.html.haml
// スマートフォン用ヘッダー
%headder.sp-header.visible-sp.has-search-nav
  .top-header
    %h1.top-header__logo
      = link_to image_tag("header-logo.svg", alt: "ヘッダーロゴ", style: "vertical-align:bottom"), root_path, class: "top-header__logo__link"

    .top-header__user-nav
      -if user_signed_in?
        = link_to image_tag("mypage_logo.png", alt: "マイページロゴ", class: "mypage-btn--small"), users_path
        = link_to "ログアウト", destroy_user_session_path, class: "logout-btn", method: :delete
      -else
        = link_to "ログイン", new_user_session_path, class: "sp-header-btn login-btn"

        = link_to "新規会員", user_registration_index_path, class: "sp-header-btn signup-btn"

  .search-bar
    = search_form_for(@q, url: search_items_path, html: { class: "search-bar__form" }) do |f|

      = f.label :name_or_description_cont, for: "search-icon" do
        %i.fa.fa-search
      = f.search_field :name_or_description_cont, class: "search-bar__form__textfield", placeholder: "何をお探しですか？"
      = f.submit "Search", id: "search-icon"

  .search-nav
    = link_to "カテゴリから探す", "#", class: "search-nav__category"

    = link_to "ブランドから探す", "#", class: "search-nav__brand"


//PC・タブレット用ヘッダー
%header.pc-header.visible-pc
  .header-container
    .top-wrapper
      %h1.top-wrapper__logo
        = link_to image_tag("header-logo.svg", width: "134", height: "36", alt: "ヘッダーロゴ", style: "vertical-align:bottom"), root_path, class: "top-wrapper__logo__img"
      = search_form_for(@q, url: search_items_path, html: { class: "top-wrapper__form" }) do |f|
        = f.label :name_or_description_cont, for: "search-icon" do
          %i.fa.fa-search
        = f.search_field :name_or_description_cont, class: "top-wrapper__form__textfield", placeholder: "キーワードから探す"
        = f.submit "Search", id: "search-icon"
    .bottom-wrapper
      %nav.left-nav
        %ul.left-nav__menu
          %li
            = link_to "カテゴリから探す", "#", class: "left-nav__menu--category"
            %ul.left-nav__menu--root-category
              - Category.roots.each do |root|
                %li
                  = link_to "#{root.name}", "#"
                  %ul.child-category
                    - Category.children_of(root).each do |child|
                      %li
                        = link_to "#{child.name}", "#"
                        %ul.grandchild-category
                          - Category.children_of(child).each do |grandchild|
                            %li
                              = link_to "#{grandchild.name}", "#"
          %li
            = link_to "ブランドから探す", "#", class: "left-nav__menu--brand"
            %ul.pickup-brand
              %li
                = link_to "シャネル", "#"
              %li
                = link_to "ナイキ", "#"
              %li
                = link_to "ルイ ヴィトン", "#"
              %li
                = link_to "シュプリーム", "#"
              %li
                = link_to "アディダス", "#"
              %li
                = link_to "ブランド一覧", "#"

      .right-nav
        %ul.right-nav__buttons
          -if user_signed_in?
            %li
              = link_to users_path, class: "mypage-btn" do
                =image_tag("mypage_logo.png", alt: "マイページロゴ", class: "mypage-btn--small")
                マイページ
              %ul.mypage-dropdown
                %li
                  .toppage-user-icon
                    = link_to users_path do
                      =image_tag("mypage_logo.png", alt: "user-icon", class: "user-icon__image", style: "vertical-align:bottom")
                      %h2.user-name
                        = current_user.nickname
                      .user-number
                        .user-number__evaluation 評価 0
                        .user-number__item-number 出品数 0
                %li
                  = link_to "出品した商品-出品中", {controller: "users", action: "edit", name: "listing"}, class: "side-nav__list__content"
                %li
                  = link_to "出品した商品-取引中", {controller: "users", action: "edit", name: "in_progress"}, class: "side-nav__list__content"
                %li
                  = link_to "出品した商品-売却済み", {controller: "users", action: "edit", name: "completed"}, class: "side-nav__list__content"

            %li
              = link_to "ログアウト", destroy_user_session_path, class: "logout-btn", method: :delete
          -else
            %li
              = link_to "ログイン", new_user_session_path, class: "pc-header-btn login-btn"

            %li
              = link_to "新規会員登録", user_registration_index_path, class: "pc-header-btn pc-signup"

app/views/shared/_items-box.html.haml
.item-box.item-box--user-item.item-box--search
  = link_to item_path(item.id) do
    - if item.order_status == "売却済"
      .item-box__photo.soldout
        = image_tag item.image.url, alt: "アイテム画像", style: "vertical-align:bottom"
    - else
      .item-box__photo
        = image_tag item.image.url, alt: "アイテム画像", style: "vertical-align:bottom"
    .item-box__body
      %h3.item-box__name=item.name
      .item-box__num
        .item-box__num__price=converting_to_jpy(item.price)
        .item-box__num__likes
          =fa_icon("heart", text: 10)
        %p (税込)

app/views/shared/_mypage-items.html.haml
%ul.mypage-item-list
  %li.mypage-item
    = link_to controller: "items", action: "edit", name: "myitem-detail", item_id: item.id do
      .mypage-item__link
        .mypage-item__link__img
          = image_tag(item.image.url, alt: "mypage-item-img")
        .mypage-item__body
          .mypage-item__body__text=item.name
          .mypage-item__body__status
            .status-label 出品中

app/views/shared/_sell_btn.html.haml
= link_to new_item_path, class: "sell-btn" do
  .sell-btn__char 出品
  =fa_icon "camera", class: "sell-btn__icon"

app/views/shared/_side-bar.html.haml
.side-bar
  .side-nav
    %ul.side-nav__list
      %li
        = link_to "マイページ", "/users", class: "side-nav__list__content"
      %li
        = link_to "お知らせ", "#", class: "side-nav__list__content"
      %li
        = link_to "やることリスト", "#", class: "side-nav__list__content"
      %li
        = link_to "いいね！一覧", "#", class: "side-nav__list__content"
      %li
        = link_to "出品する", "/items/new", class: "side-nav__list__content"
      %li
        = link_to "出品した商品-出品中", {controller: "users", action: "edit", name: "listing"}, class: "side-nav__list__content"
      %li
        = link_to "出品した商品-取引中", {controller: "users", action: "edit", name: "in_progress"}, class: "side-nav__list__content"
      %li
        = link_to "出品した商品-売却済み", {controller: "users", action: "edit", name: "completed"}, class: "side-nav__list__content"
      %li
        = link_to "購入した商品-取引中", "#", class: "side-nav__list__content"
      %li
        = link_to "購入した商品-過去の取引", "#", class: "side-nav__list__content"
      %li
        = link_to "ニュース一覧", "#", class: "side-nav__list__content"
      %li
        = link_to "評価一覧", "#", class: "side-nav__list__content"
      %li
        = link_to "ガイド", "#", class: "side-nav__list__content"
      %li
        = link_to "お問い合わせ", "#", class: "side-nav__list__content"


    %h3.side-nav__head 売上・ポイント
    %ul.side-nav__list
      %li
        = link_to "売上・振込申請", "#", class: "side-nav__list__content"
      %li
        = link_to "ポイント", "#", class: "side-nav__list__content"

    %h3.side-nav__head 設定
    %ul.side-nav__list
      %li
        = link_to "プロフィール", {controller: "users/registrations", action: "edit", name: "profile"}, class: "side-nav__list__content"
      %li
        = link_to "本人情報", {controller: "users/registrations", action: "edit", name: "deliver_address"}, class: "side-nav__list__content"
      %li
        = link_to "支払い方法", {controller: "users/registrations", action: "edit", name: "creditcard"}, class: "side-nav__list__content"
      %li
        = link_to "メール/パスワード", {controller: "users/registrations", action: "edit", name: "email_password"}, class: "side-nav__list__content"
      %li
        = link_to "電話番号の確認", {controller: "users", action: "edit", name: "sms_confirmation"}, class: "side-nav__list__content"

app/views/shared/_soldout-items.html.haml
-if item[:order_status] == "売却済"
  %ul.mypage-item-list
    %li.mypage-item
      = link_to controller: "items", action: "edit", name: "myitem-detail", item_id: item.id do
        .mypage-item__link
          .mypage-item__link__img
            = image_tag(item.image.url, alt: "mypage-item-img")
          .mypage-item__body
            .mypage-item__body__text=item.name
            .mypage-item__body__status
              .status-label--sold 売却済

app/views/shared/_sub-footer.html.haml
%footer.single-footer
  %nav
    %ul
      %li
        =link_to "プライバシーポリシー","https://www.google.com", class: "critical_information"
      %li
        =link_to "メルカリ利用規約","https://www.google.com", class: "critical_information"
      %li
        =link_to "特定商取引に関する表記","https://www.google.com", class: "critical_information"
  = link_to image_tag("admin_footer_logo.svg", alt: "Mercari", class: "single-footer-logo"), root_path
  %p
    %small © 2019 Mercari

app/views/shared/_sub-header.html.haml
.single-container
  %header.single-header
    = link_to image_tag("header-logo.svg", alt: "Mercari", class: "single-header-logo"), root_path

app/views/shared/_user_flash_error.html.haml
- if flash[:success_update]
  :javascript
    toastr.options = {
      "progressBar": true,
      "positionClass": "toast-top-full-width",
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    };
    toastr.success("変更しました")
-elsif flash[:fail_update]
  :javascript
    toastr.options = {
      "progressBar": true,
      "positionClass": "toast-top-full-width",
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    };
    toastr.error("変更に失敗しました")