config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  root "items#index"
  resources :items, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :orders, only: [:new, :create]
    get '/:name', controller: 'items', action: 'edit'
    get 'search', on: :collection
  end



  devise_scope :user do
    get "/users/sign_up/registration", to: "users/registrations#index", as: "user_registration_index"
    get "/users/sign_up/basic-infomation", to: "users/registrations#basic_information", as: "user_registration_basic_infomation"
    get "/users/sign_up/sns-basic-infomation", to: "users/registrations#sns_basic_information", as: "user_registration_sns_basic_infomation"
    get "/users/sign_up/residence", to: "users/registrations#residence", as: "user_registration_residence"
    get "/users/sign_up/payment", to: "users/registrations#payment", as: "user_registration_payment"
    post '/users/sign_up/payment/finish', to: "users/registrations#finish", as: "user_registration_finish"
    patch 'users/:name', controller: 'users/registrations', action: 'update'
  end

  resource :users, only: [:show, :update]

  get 'users/:name', controller: 'users', action: 'edit'
  get 'users/:name', controller: 'users/registrations', action: 'edit'
end

app/models/item.rb
class Item < ApplicationRecord

  validates :image, presence: { message: '画像がありません' }
  validates :name, presence: true, length: {maximum: 40, allow_blank: true, message: "40文字以下で入力してください"}
  validates :description, presence: true, length: {maximum: 1000, allow_blank:true, message: "1000文字以下で入力してください"}
  validates :order_status, presence: { message: '選択してください' }
  validates :item_status, presence: { message: '選択してください' }
  validates :shipping_fee, presence: { message: '選択してください' }
  validates :delivery_way, presence: { message: '選択してください' }
  validates :shipping_area, presence: { message: '選択してください' }
  validates :estimated_shipping_date, presence: { message: '選択してください' }
  validates :price, presence: {message: "300以上9999999以下で入力してください"}, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, allow_blank: true, message: "300以上9999999以下で入力してください"}

  validates :category_id, presence: { message: '選択してください' }

  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :category
  belongs_to :brand, optional: true

  has_one :order, dependent: :destroy

  enum size: { "XXS以下": "XXS以下", "XS(SS)": "XS(SS)", "S": "S", "M": "M", "L": "L", "XL(LL)": "XL(LL)", "2XL(3L)": "2XL(3L)", "3XL(4L)": "3XL(4L)", "4XL(5L)以上": "4XL(5L)以上", "FREE SIZE": "FREE SIZE"}

  enum item_status: {"新品、未使用": "新品、未使用", "未使用に近い": "未使用に近い", "目立った傷や汚れなし": "目立った傷や汚れなし", "やや傷や汚れあり": "やや傷や汚れあり", "傷や汚れあり": "傷や汚れあり", "全体的に状態が悪い": "全体的に状態が悪い"}

  enum shipping_fee: {"送料込み(出品者負担)": "送料込み(出品者負担)", "着払い(購入者負担)": "着払い(購入者負担)"}

  enum delivery_way: { "未定": "未定", "らくらくメルカリ便": "らくらくメルカリ便", "ゆうメール": "ゆうメール", "レターパック": "レターパック", "普通郵便(定形、定形外)": "普通郵便(定形、定形外)", "クロネコヤマト": "クロネコヤマト", "ゆうパック": "ゆうパック", "クリックポスト": "クリックポスト", "ゆうパケット": "ゆうパケット"}

  enum estimated_shipping_date: { "1〜2日で発送": "1〜2日で発送", "2〜3日で発送": "2〜3日で発送", "4〜7日で発送": "4〜7日で発送"}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_item, only: [:show, :update, :destroy]
  before_action :set_edit_item, only: [:edit]
  before_action :set_search_val, only: [:index, :show, :edit, :create, :update, :destroy, :search]
  before_action :set_pickup_items, only: [:index, :create]

  def index
  end

  def search
    @q = Item.search(search_params)
    set_serchitems_and_count(@q)
  end

  def new
    @item = Item.new
  end

  def create
    begin
      Item.transaction do
      # ブランドをデータベースから検索
        search_brand_id = ""
        brand_id = item_params[:brand_id]
        category_id = item_params[:category_id]

        if brand_id.present?
          search_brand = Brand.where("name LIKE(?)", brand_id)
          search_brand_id = search_brand[0].id if search_brand != []
        end

        if search_brand_id.present?
          # もしブランドがデータベース内に見つかった時
          # カテゴリと紐付いているブランドが同一か確認
          session[:final_params] = add_brand(item_params, search_brand_id)
          search_category_id = CategoryBrand.where("brand_id LIKE(?) and category_id LIKE(?)", session[:final_params][:brand_id], category_id)
          # カテゴリブランドが紐付いていない時、中間テーブルに登録
          CategoryBrand.create!(brand_id: session[:final_params][:brand_id], category_id: category_id) if search_category_id.empty?
        else
          # もしブランドがデータベースになかった時
          if brand_id.present?
            @brand_id = Brand.create!(name: brand_id).id
            CategoryBrand.create!(brand_id: @brand_id, category_id: category_id)
          else
            @brand_id = nil
          end
          session[:final_params] = add_brand(item_params, @brand_id)
        end
      end

      # brand-categoryの受け渡しがうまくいったら、アイテムを生成
        @item = Item.new(session[:final_params])
        session[:final_params] = nil
        if @item.save
          flash.now[:notice_exhibition_completed] = "出品が完了しました"
          render "items/index"
        else
          render :new
        end
    rescue => e
      # brand-categoryの受け渡しが一つでも上手くいかなかった時
      # 全てロールバックさせる
      Rails.logger.debug e.message
      flash[:notice_brand_registration] = "ブランドの登録に失敗しました"
      @item = Item.new(item_params)
      render :new
    end
  end

  def show
    @items = Item.where("order_status = '出品中'")
  end

  def edit
    render "items/#{params[:name]}"
  end

  def update
    begin
      Item.transaction do
      # ブランドをデータベースから検索
        search_brand_id = ""
        brand_id = item_params[:brand_id]
        category_id = item_params[:category_id]

        if brand_id.present?
          search_brand = Brand.where("name LIKE(?)", brand_id)
          search_brand_id = search_brand[0].id if search_brand != []
        end

        if search_brand_id.present?
          # もしブランドがデータベース内に見つかった時
          # カテゴリと紐付いているブランドが同一か確認
          session[:final_params] = add_brand(item_params, search_brand_id)
          search_category_id = CategoryBrand.where("brand_id LIKE(?) and category_id LIKE(?)", session[:final_params][:brand_id], category_id)
          # カテゴリブランドが紐付いていない時、中間テーブルに登録
          CategoryBrand.create!(brand_id: session[:final_params][:brand_id], category_id: category_id) if search_category_id.empty?
        else
          # もしブランドがデータベースになかった時
          if brand_id.present?
            @brand_id = Brand.create!(name: brand_id).id
            CategoryBrand.create!(brand_id: @brand_id, category_id: category_id)
          else
            @brand_id = nil
          end
          session[:final_params] = add_brand(item_params, @brand_id)
        end
      end

      # brand-categoryの受け渡しがうまくいったら、アイテムを生成
        final_params = session[:final_params]
        session[:final_params] = nil
        if @item.user.id == current_user.id
          if @item.update(final_params)
            flash.now[:notice_updated] = "商品の情報を更新しました"
            render "items/myitem-detail"
          else
            render "items/edit"
          end
        end
    rescue => e
      # brand-categoryの受け渡しが一つでも上手くいかなかった時
      # 全てロールバックさせる
      Rails.logger.debug e.message
      flash[:notice_brand_registration] = "ブランドの登録に失敗しました"
      @item = Item.new(item_params)
      render :new
    end

  end

  def destroy
    @item.destroy if @item.user_id == current_user.id
      flash.now[:notice_deleted] = "商品を削除しました"
      render "users/listing", locals: {user: current_user }
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :price, :order_status, :item_status, :shipping_fee, :delivery_way, :shipping_area, :estimated_shipping_date, :description, :size, :category_id, :brand_id).merge(user_id: current_user.id)
  end

  def add_brand(params_no_brand, brand_id)
    params_no_brand.merge(brand_id: brand_id)
  end

  def display_category(category_parent_id)
    Item.joins(:category).where("categories.ancestry LIKE ?", "#{category_parent_id}%").order("created_at DESC").page(params[:page]).per(4)
  end

  def display_brand(brand_name)
    Item.joins(:brand).where("brands.name LIKE ?", "%#{brand_name}%").order("created_at DESC").page(params[:page]).per(4)
  end

  def set_search_val
    @q = Item.ransack(params[:q])
    set_serchitems_and_count(@q)
  end

  def search_params
    params.require(:q).permit(:name_or_description_cont)
  end

  def set_serchitems_and_count(search_query)
    @categories = Category.all
    @items = search_query.result.includes(:category, :brand).page(params[:page]).per(48)
    @count = @items.total_count
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_edit_item
    @item = Item.find(params[:item_id])
  end

  def set_pickup_items
    @pickup_category_items_1 = display_category("1")
    @pickup_category_items_2 = display_category("2")
    @pickup_brand_items_1 = display_brand("シャネル")
    @pickup_brand_items_2 = display_brand("ナイキ")
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def converting_to_jpy(price)
    "¥ #{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/items/edit.html.haml
= render "shared/sub-header"

.sell-main
  .item-information
    %h2.innertitle 商品の情報を入力


    = form_for @item, builder: ApplicationFormBuilder, html: {class: "item-information__form-inner"}do |f|

      .sell-upload-box
        = f.label :image, class: "item-label" do
          出品画像
          %span.required 必須
          %p 画像をアップロードしてください。
        = f.file_field :image, class: "sell-dropbox-container"

      .sell-content
        .form-group
          = f.label :name, class: "item-label" do
            商品名
            %span.required 必須
          = f.text_field :name, placeholder: "商品名(必須40文字まで)", class: "form-group__form-default"
          - if @item.errors.any?
            %li.errors
              = @item.errors.full_messages_for(:name)[0]

        .form-group
          = f.label :description, class: "item-label" do
            商品の説明
            %span.required 必須
          = f.text_area :description, placeholder: "商品の説明(必須1,000文字以内) (色、素材、重さ、定価、注意点など) 例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。", class: "form-group__form-default textarea-default"

      .sell-content
        %h3.sell-sub-head 商品の詳細

        .sell-form-box
          .form-group
            = f.label :category_id, class: "item-label" do
              カテゴリー
              %span.required 必須

            =f.collection_select :category_id, Category.roots, :id, :name, { prompt: "---" }, {class: "select-default root_category"}

          %div
            - Category.roots.each do |root_category|
              %template{id: "child_of#{ root_category.id }"}
                =f.collection_select :category_id, root_category.children, :id, :name, { prompt: "---" }, {class: "select-default child_categories"}

          %div
            - Category.roots.each do |root_category|
              - Category.children_of(root_category).each do |child_category|
                %template{id: "child_of#{ child_category.id }"}
                  = f.collection_select :category_id, child_category.children, :id, :name, { prompt: "---" }, {class: "select-default grand-child_categories"}

          .form-group#sml-size
            = f.label :size, class: "item-label" do
              サイズ
              %span.any 任意
            = f.enum_select :size, prompt: "---", class: "select-default"

          .form-group
            = f.label :brand_id, class: "item-label" do
              ブランド
              %span.any 任意
            = f.text_field :brand_id, placeholder: "例) シャネル", value: "#{@item.brand.name if @item.brand.present?}", class: "form-group__form-default"
            =flash[:notice_brand_registration]

          .form-group
            = f.label :item_status, class: "item-label" do
              商品の状態
              %span.required 必須
            = f.enum_select :item_status, prompt: "---"

      .sell-content
        %h3.sell-sub-head 配送について

        .sell-form-box
          .form-group
            = f.label :shipping_fee, class: "item-label" do
              配送量の負担
              %span.required 必須
            = f.enum_select :shipping_fee, prompt: "---"

          .form-group
            = f.label :delivery_way, class: "item-label" do
              配送の方法
              %span.required 必須
            = f.enum_select :delivery_way, prompt: "---"

          .form-group
            = f.label :shipping_area, class: "item-label" do
              発送元の地域
              %span.required 必須
            = f.collection_select :shipping_area, JpPrefecture::Prefecture.all, :name, :name, include_blank: true, prompt: "---"

          .form-group
            = f.label :estimated_shipping_date, class: "item-label" do
              発送までの日数
              %span.required 必須
            = f.enum_select :estimated_shipping_date,  prompt: "---"

      .sell-content
        %h3.sell-sub-head 販売価格(300〜9,999,999)

        .sell-form-box
          %ul.sell-price
            %li
              = f.label :price, class: "item-label l-left" do
                価格
                %span.required 必須
              .l-right
                ¥
                .l-right__form
                  = f.text_field :price, placeholder: "例) 300", class: "form-group__form-default price-form"

            - if @item.errors.any?
              %li.errors
                = @item.errors.full_messages_for(:price)[0]

            %li.commissions
              .l-left 販売手数料(10％)
              .l-right -
            %li.profit
              .l-left 販売利益
              .l-right -

      .sell-content
        %p 禁止されている出品、行為は必ずご確認ください。
        %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        %p また。出品をもちまして加盟店規約に同意したことになります。
        = f.submit "変更する", class: "submit-btn"
        = link_to "キャンセル", root_path, class: "return-btn"

= render "shared/sub-footer"

app/views/items/index.html.haml
/ ヘッダー
= render "shared/header"

= render "shared/flash_exhibition_completed"

/ スライド
%ul.bxslider
  %li
    = image_tag("slide1.png", alt: "スライド1", style: "vertical-align:bottom")
  %li
    = image_tag("slide2.png", alt: "スライド2", style: "vertical-align:bottom")
  %li
    = image_tag("slide3.png", alt: "スライド3", style: "vertical-align:bottom")
  %li
    = image_tag("slide4.png", alt: "スライド4", style: "vertical-align:bottom")
  %li
    = image_tag("slide5.png", alt: "スライド5", style: "vertical-align:bottom")

/ 全ての商品一覧

.item-list

  %h2.item-group ピックアップカテゴリー

  .item-container
    %h3
      = link_to "レディース 新着アイテム", "#"

    .item
      = render partial: 'shared/items-box', collection: @pickup_category_items_1, as: "item"

    .allitem-link
      %a{href: "#"} すべての商品を見る

  .item-container
    %h3
      = link_to "メンズ 新着アイテム", "#"

    .item
      = render partial: 'shared/items-box', collection: @pickup_category_items_2, as: "item"

    .allitem-link
      %a{href: "#"} すべての商品を見る


.item-list

  %h2.item-group ピックアップブランド

  .item-container
    %h3
      = link_to "シャネル 新着アイテム", "#"

    .item
      = render partial: 'shared/items-box', collection: @pickup_brand_items_1, as: "item"

    .allitem-link
      %a{href: "#"} すべての商品を見る

  .item-container
    %h3
      = link_to "ナイキ 新着アイテム", "#"

    .item
      = render partial: 'shared/items-box', collection: @pickup_brand_items_2, as: "item"

    .allitem-link
      %a{href: "#"} すべての商品を見る

/ バナー
.app-banner


/ フッター

= render "shared/footer"

= render "shared/sell_btn"

app/views/items/search.html.haml
= render 'shared/header'

.main-container
  .mypage-container
    .main-column
      - if @count == 0
        %h2.search-result 検索結果 0件
        %p.no-result 該当する商品が見つかりません。商品は毎日増えていますので、これからの出品に期待してください。
      - else
        %h2.search-result= "検索結果 1-#{ @count } 件"
      .item-list.item-list--search
        .item-container.search-item-container
          .item
            = render partial: 'shared/items-box', collection: @items, as: "item"

    .side-bar
      .side-nav
        = form_tag search_items_path, method: :get do
          = select_tag 'page[name]', options_for_select([["並び替え", "default"], ["価格の安い順", "price_asc"], ["価格の高い順", "price_desc"], ["出品の古い順", "sell_asc"], ["出品の新しい順", "sell_desc"]], class: 'order_sort')
        .search-conditionbox
          %h2.search-conditionbox__detail 詳細検索
          = search_form_for(@q, url: search_items_path) do |f|
            = f.label :name_or_description_cont, class: "search-conditionbox__addition" do
              %i.fa.fa-plus
              キーワードを追加する
            = f.search_field :name_or_description_cont, placeholder: "例） 値下げ"

            = f.label :category_id_eq, class: "search-conditionbox__addition" do
              %i.fa.fa-list
              カテゴリーを選択する
            = f.collection_select :category_id_eq, @categories, :id, :name, include_blank: 'すべて'

            = f.label :brand_id_cont, class: "search-conditionbox__addition" do
              %i.fa.fa-tag
              ブランド名から探す
            = f.search_field :brand_id_cont, placeholder: "例） シャネル"

            = f.label :size_cont, class: "search-conditionbox__addition" do
              %i.fa.fa-square
              サイズを指定する
            = f.search_field :size_cont, placeholder: "例） すべて"

            = f.label :price_cont, class: "search-conditionbox__addition" do
              %i.fa.fa-money
              価格
            = f.search_field :name_or_description_cont, placeholder: "選択してください"

            = f.label :order_status, class: "search-conditionbox__addition" do
              %i.fa.fa-star
              商品の状態
            .checkbox__container
              - %w(すべて 新品、未使用 未使用に近い 目立った傷や汚れなし やや傷や汚れあり 傷や汚れあり 全体的に状態が悪い).each.with_index do |order_status,i|
                .checkbox__default
                  %label
                    = check_box_tag 'search[order_status][]', order_status,false,class: "checkbox-default__input_#{i}"
                    %p.checkbox-default__label= order_status

            = f.label :delivery_way, class: "search-conditionbox__addition" do
              %i.fa.fa-truck
              配送料の負担
            .checkbox__container
              - %w(すべて 着払い(購入者負担) 送料込み(出品者負担)).each.with_index do |delivery_way,i|
                .checkbox__default
                  %label
                    = check_box_tag 'search[delivery_way][]', delivery_way,false,class: "checkbox-default__input_#{i}"
                    %p.checkbox-default__label= delivery_way

            = f.label :order_status, class: "search-conditionbox__addition" do
              %i.fa.fa-shopping-cart
              販売状況
            .checkbox__container
              - %w(すべて 出品中 売却済).each.with_index do |order_status,i|
                .checkbox__default
                  %label
                    = check_box_tag 'search[order_status][]', order_status,false,class: "checkbox-default__input_#{i}"
                    %p.checkbox-default__label= order_status
            .send-field
              = tag :input, type: 'reset', value: 'クリア', class: "search-conditionbox__clear-btn"
              = tag :input, type: 'submit', value: '完了', class: "search-conditionbox__finish-btn"
.app-banner

= render 'shared/footer'

= render 'shared/sell_btn'

app/views/items/show.html.haml
/ ヘッダー
= render "shared/header"

.item-list
  .single-main
    .item-detail
      %h1.item-detail__name
        =@item.name
      .item-detail__main-contents.main-contents
        .main-contents__PhotoAndDetail
          %section.main-contents__photo
            =image_tag(@item.image.url, class: "item-main-photo")
            .item-sub-photo
          %section.main-contents__detail.main-contents__detail--large
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    =link_to @item.user.nickname, "#"
                    %br
                    .item-user-eva
                      %i.fa.fa-smile-o.smile
                      78
                    .item-user-eva
                      %i.fa.fa-meh-o.meh
                      10
                    .item-user-eva
                      %i.fa.fa-frown-o.frown
                      10
                %tr
                  %th カテゴリー
                  %td
                    =link_to @item.category.ancestors[0].name, "#" if @item.category.ancestors[0].present?
                    %br
                    =link_to @item.category.ancestors[1].name, "#" if @item.category.ancestors[1].present?
                    %br
                    =link_to @item.category.name, "#"
                %tr
                  %th ブランド
                  %td
                    =link_to @item.brand.name, "#" if @item.brand.present?
                %tr
                  %th 商品のサイズ
                  %td
                    = @item.size
                %tr
                  %th 商品の状態
                  %td
                    =@item.item_status
                %tr
                  %th 配送料の負担
                  %td
                    =@item.shipping_fee
                %tr
                  %th 配送の方法
                  %td
                    =@item.delivery_way
                %tr
                  %th 配送元地域
                  %td
                    =link_to @item.user.prefecture, "#"
                %tr
                  %th 発送日の目安
                  %td
                    =@item.estimated_shipping_date
      .item-detail__price-box
        %span.item-price=converting_to_jpy(@item.price)
        %span.item-tax (税込)
        %span.item-shipping-fee 送料込み
      - if @item.order_status == "売却済"
        .item-detail__item-buy-button
          %p.btn-sold 売り切れました
      - else
        .item-detail__item-buy-button
          =link_to "購入画面に進む", new_item_order_url(@item.id), class: "btn-buy"
        %section.main-contents__detail.main-contents__detail--small
          %table
            %tbody
              %tr
                %th 出品者
                %td
                  =link_to @item.user.nickname, "#"
                  %br
                  .item-user-eva
                    %i.fa.fa-smile-o.smile
                    78
                  .item-user-eva
                    %i.fa.fa-meh-o.meh
                    10
                  .item-user-eva
                    %i.fa.fa-frown-o.frown
                    10
              %tr
                %th カテゴリー
                %td
                  =link_to @item.category.ancestors[0].name, "#" if @item.category.ancestors[0].present?
                  %br
                  =link_to @item.category.ancestors[1].name, "#" if @item.category.ancestors[1].present?
                  %br
                  =link_to @item.category.name, "#" if @item.brand.present?
              %tr
                %th ブランド
                %td ナノ ユニバース
              %tr
                %th 商品のサイズ
                %td
                  =@item.size
              %tr
                %th 商品の状態
                %td
                  = @item.item_status
              %tr
                %th 配送料の負担
                %td
                  = @item.shipping_fee
              %tr
                %th 配送の方法
                %td
                  = @item.delivery_way
              %tr
                %th 配送元地域
                %td
                  =link_to @item.user.prefecture, "#"
              %tr
                %th 発送日の目安
                %td
                  = @item.estimated_shipping_date
      .item-detail__price-box.item-detail__price-box--small
        %span.item-price=converting_to_jpy(@item.price)
        %span.item-tax (税込)
        %span.item-shipping-fee 送料込み
      - if @item.order_status == "売却済"
        .item-detail__item-buy-button.item-detail__item-buy-button--small
          %p.btn-sold 売り切れました
      - else
        .item-detail__item-buy-button.item-detail__item-buy-button--small
          =link_to "購入画面に進む", new_item_order_url(@item.id), class: "btn-buy"
      .item-detail__description
        %p.description-inner=@item.description
      .item-detail__sub-buttons
        %button.btn-tag-like
          %i.fa.fa-heart-o
          いいね
        %button.btn-tag-unfitable
          %i.fa.fa-flag-o
          不適切な商品の報告
        =link_to "#", class: "safty" do
          %i.fa.fa-lock
          あんしん・あんぜんへの取り組み
    .comment-container
      .comment-container__comment-view.comment-view
        = link_to image_tag("", alt: "", class: "comment-view__user_image")
        .comment-view__user-name Natalia
        .comment-view__balloom
          すみません、どんなファーでしょうか？
          .comment-time
            %i.fa.fa-clock-o
            3日前
          .comment-flag
            %i.fa.fa-flag-o
      %form{action: "/", method: "post"}
        %p.comment-container__attention 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea.comment-container__textarea
        - if @item.order_status == "売却済"
          %p.comment-container__button--sold 売り切れのためコメントできません
        - else
          %input{type: "submit", value: "コメントする", class: "comment-container__button"}

    %nav.item-paginate
      %ul
        %li.item-paginate__prev
          =link_to "#" do
            %i.fa.fa-chevron-left
            テラフォーマーズ 1〜19巻セット
        %li.item-paginate__next
          =link_to "#" do
            ねこのかぶりもの ロコン
            %i.fa.fa-chevron-right
    .sns-container
      .sns-box
        .facebook
          %i.fa.fa-facebook-square
        .twitter
          %i.fa.fa-twitter
        .pinterest
          %i.fa.fa-pinterest

    .user-item-container
      %h3
        = link_to "#{@item.user.nickname}さんのその他の出品", "#"
      .item
        = render partial: 'shared/items-box', collection: @items, as: "item"
/ バナー
.app-banner

/ フッター
= render "shared/footer"